import { Header } from "@/components/home/Header";
import "./globals.css";
import { UserProvider } from "@/provider/UserProvider";

export const metadata = {
  title: "income expense",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <UserProvider>{children}</UserProvider>
      </body>
    </html>
  );
}
